/**
 * Noms de pays FR/EN par code ISO 3166-1 alpha-2 (clé des CSCA du magasin embarqué). Générés depuis
 * le paquet i18n-iso-countries 7.14.0 (langs/fr.json, langs/en.json) — Hermes n'a pas
 * Intl.DisplayNames, d'où cette table statique.
 */
import { toAlpha2CountryCode } from "@emrtd-verify/emrtd-core";

export const COUNTRY_NAMES: Record<string, [fr: string, en: string]> = {
  AD: ["Andorre", "Andorra"],
  AE: ["Émirats Arabes Unis", "United Arab Emirates"],
  AF: ["Afghanistan", "Afghanistan"],
  AG: ["Antigua-et-Barbuda", "Antigua and Barbuda"],
  AI: ["Anguilla", "Anguilla"],
  AL: ["Albanie", "Albania"],
  AM: ["Arménie", "Armenia"],
  AO: ["Angola", "Angola"],
  AQ: ["Antarctique", "Antarctica"],
  AR: ["Argentine", "Argentina"],
  AS: ["Samoa américaines", "American Samoa"],
  AT: ["Autriche", "Austria"],
  AU: ["Australie", "Australia"],
  AW: ["Aruba", "Aruba"],
  AX: ["Åland", "Åland Islands"],
  AZ: ["Azerbaïdjan", "Azerbaijan"],
  BA: ["Bosnie-Herzégovine", "Bosnia and Herzegovina"],
  BB: ["Barbade", "Barbados"],
  BD: ["Bangladesh", "Bangladesh"],
  BE: ["Belgique", "Belgium"],
  BF: ["Burkina Faso", "Burkina Faso"],
  BG: ["Bulgarie", "Bulgaria"],
  BH: ["Bahreïn", "Bahrain"],
  BI: ["Burundi", "Burundi"],
  BJ: ["Bénin", "Benin"],
  BL: ["Saint-Barthélemy", "Saint Barthélemy"],
  BM: ["Bermudes", "Bermuda"],
  BN: ["Brunei Darussalam", "Brunei Darussalam"],
  BO: ["Bolivie", "Bolivia"],
  BQ: ["Bonaire, Saint-Eustache et Saba", "Bonaire, Sint Eustatius and Saba"],
  BR: ["Brésil", "Brazil"],
  BS: ["Bahamas", "Bahamas"],
  BT: ["Bhoutan", "Bhutan"],
  BV: ["Île Bouvet", "Bouvet Island"],
  BW: ["Botswana", "Botswana"],
  BY: ["Biélorussie", "Belarus"],
  BZ: ["Belize", "Belize"],
  CA: ["Canada", "Canada"],
  CC: ["Îles Cocos", "Cocos (Keeling) Islands"],
  CD: ["République démocratique du Congo", "Democratic Republic of the Congo"],
  CF: ["République Centrafricaine", "Central African Republic"],
  CG: ["République du Congo", "Republic of the Congo"],
  CH: ["Suisse", "Switzerland"],
  CI: ["Côte-d'Ivoire", "Cote d'Ivoire"],
  CK: ["Îles Cook", "Cook Islands"],
  CL: ["Chili", "Chile"],
  CM: ["Cameroun", "Cameroon"],
  CN: ["Chine", "People's Republic of China"],
  CO: ["Colombie", "Colombia"],
  CR: ["Costa Rica", "Costa Rica"],
  CU: ["Cuba", "Cuba"],
  CV: ["Cap-Vert", "Cape Verde"],
  CW: ["Curaçao", "Curaçao"],
  CX: ["Île Christmas", "Christmas Island"],
  CY: ["Chypre", "Cyprus"],
  CZ: ["République Tchèque", "Czech Republic"],
  DE: ["Allemagne", "Germany"],
  DJ: ["Djibouti", "Djibouti"],
  DK: ["Danemark", "Denmark"],
  DM: ["Dominique", "Dominica"],
  DO: ["République Dominicaine", "Dominican Republic"],
  DZ: ["Algérie", "Algeria"],
  EC: ["Équateur", "Ecuador"],
  EE: ["Estonie", "Estonia"],
  EG: ["Égypte", "Egypt"],
  EH: ["Sahara occidental", "Western Sahara"],
  ER: ["Érythrée", "Eritrea"],
  ES: ["Espagne", "Spain"],
  ET: ["Éthiopie", "Ethiopia"],
  FI: ["Finlande", "Finland"],
  FJ: ["Fidji", "Fiji"],
  FK: ["Îles Malouines", "Falkland Islands (Malvinas)"],
  FM: ["Micronésie", "Micronesia, Federated States of"],
  FO: ["Îles Féroé", "Faroe Islands"],
  FR: ["France", "France"],
  GA: ["Gabon", "Gabon"],
  GB: ["Royaume-Uni", "United Kingdom"],
  GD: ["Grenade", "Grenada"],
  GE: ["Géorgie", "Georgia"],
  GF: ["Guyane française", "French Guiana"],
  GG: ["Guernesey", "Guernsey"],
  GH: ["Ghana", "Ghana"],
  GI: ["Gibraltar", "Gibraltar"],
  GL: ["Groenland", "Greenland"],
  GM: ["Gambie", "Republic of The Gambia"],
  GN: ["Guinée", "Guinea"],
  GP: ["Guadeloupe", "Guadeloupe"],
  GQ: ["Guinée équatoriale", "Equatorial Guinea"],
  GR: ["Grèce", "Greece"],
  GS: ["Géorgie du Sud-et-les Îles Sandwich du Sud", "South Georgia and the South Sandwich Islands"],
  GT: ["Guatemala", "Guatemala"],
  GU: ["Guam", "Guam"],
  GW: ["Guinée-Bissau", "Guinea-Bissau"],
  GY: ["Guyana", "Guyana"],
  HK: ["Hong Kong", "Hong Kong"],
  HM: ["Îles Heard-et-MacDonald", "Heard Island and McDonald Islands"],
  HN: ["Honduras", "Honduras"],
  HR: ["Croatie", "Croatia"],
  HT: ["Haïti", "Haiti"],
  HU: ["Hongrie", "Hungary"],
  ID: ["Indonésie", "Indonesia"],
  IE: ["Irlande", "Ireland"],
  IL: ["Israël", "Israel"],
  IM: ["Île de Man", "Isle of Man"],
  IN: ["Inde", "India"],
  IO: ["Océan Indien Britannique", "British Indian Ocean Territory"],
  IQ: ["Irak", "Iraq"],
  IR: ["Iran", "Islamic Republic of Iran"],
  IS: ["Islande", "Iceland"],
  IT: ["Italie", "Italy"],
  JE: ["Jersey", "Jersey"],
  JM: ["Jamaïque", "Jamaica"],
  JO: ["Jordanie", "Jordan"],
  JP: ["Japon", "Japan"],
  KE: ["Kenya", "Kenya"],
  KG: ["Kirghizistan", "Kyrgyzstan"],
  KH: ["Cambodge", "Cambodia"],
  KI: ["Kiribati", "Kiribati"],
  KM: ["Comores", "Comoros"],
  KN: ["Saint-Christophe-et-Niévès", "Saint Kitts and Nevis"],
  KP: ["Corée du Nord", "North Korea"],
  KR: ["Corée du Sud", "South Korea"],
  KW: ["Koweït", "Kuwait"],
  KY: ["Îles Caïmans", "Cayman Islands"],
  KZ: ["Kazakhstan", "Kazakhstan"],
  LA: ["Laos", "Lao People's Democratic Republic"],
  LB: ["Liban", "Lebanon"],
  LC: ["Sainte-Lucie", "Saint Lucia"],
  LI: ["Liechtenstein", "Liechtenstein"],
  LK: ["Sri Lanka", "Sri Lanka"],
  LR: ["Libéria", "Liberia"],
  LS: ["Lesotho", "Lesotho"],
  LT: ["Lituanie", "Lithuania"],
  LU: ["Luxembourg", "Luxembourg"],
  LV: ["Lettonie", "Latvia"],
  LY: ["Libye", "Libya"],
  MA: ["Maroc", "Morocco"],
  MC: ["Monaco", "Monaco"],
  MD: ["Moldavie", "Moldova, Republic of"],
  ME: ["Monténégro", "Montenegro"],
  MF: ["Saint-Martin (partie française)", "Saint Martin (French part)"],
  MG: ["Madagascar", "Madagascar"],
  MH: ["Îles Marshall", "Marshall Islands"],
  MK: ["Macédoine du Nord", "The Republic of North Macedonia"],
  ML: ["Mali", "Mali"],
  MM: ["Myanmar", "Myanmar"],
  MN: ["Mongolie", "Mongolia"],
  MO: ["Macao", "Macao"],
  MP: ["Îles Mariannes du Nord", "Northern Mariana Islands"],
  MQ: ["Martinique", "Martinique"],
  MR: ["Mauritanie", "Mauritania"],
  MS: ["Montserrat", "Montserrat"],
  MT: ["Malte", "Malta"],
  MU: ["Maurice", "Mauritius"],
  MV: ["Maldives", "Maldives"],
  MW: ["Malawi", "Malawi"],
  MX: ["Mexique", "Mexico"],
  MY: ["Malaisie", "Malaysia"],
  MZ: ["Mozambique", "Mozambique"],
  NA: ["Namibie", "Namibia"],
  NC: ["Nouvelle-Calédonie", "New Caledonia"],
  NE: ["Niger", "Niger"],
  NF: ["Île Norfolk", "Norfolk Island"],
  NG: ["Nigéria", "Nigeria"],
  NI: ["Nicaragua", "Nicaragua"],
  NL: ["Pays-Bas", "Netherlands"],
  NO: ["Norvège", "Norway"],
  NP: ["Népal", "Nepal"],
  NR: ["Nauru", "Nauru"],
  NU: ["Niué", "Niue"],
  NZ: ["Nouvelle-Zélande", "New Zealand"],
  OM: ["Oman", "Oman"],
  PA: ["Panama", "Panama"],
  PE: ["Pérou", "Peru"],
  PF: ["Polynésie française", "French Polynesia"],
  PG: ["Papouasie-Nouvelle-Guinée", "Papua New Guinea"],
  PH: ["Philippines", "Philippines"],
  PK: ["Pakistan", "Pakistan"],
  PL: ["Pologne", "Poland"],
  PM: ["Saint-Pierre-et-Miquelon", "Saint Pierre and Miquelon"],
  PN: ["Îles Pitcairn", "Pitcairn"],
  PR: ["Porto Rico", "Puerto Rico"],
  PS: ["Palestine", "State of Palestine"],
  PT: ["Portugal", "Portugal"],
  PW: ["Palaos", "Palau"],
  PY: ["Paraguay", "Paraguay"],
  QA: ["Qatar", "Qatar"],
  RE: ["Réunion", "Reunion"],
  RO: ["Roumanie", "Romania"],
  RS: ["Serbie", "Serbia"],
  RU: ["Russie", "Russian Federation"],
  RW: ["Rwanda", "Rwanda"],
  SA: ["Arabie Saoudite", "Saudi Arabia"],
  SB: ["Îles Salomon", "Solomon Islands"],
  SC: ["Seychelles", "Seychelles"],
  SD: ["Soudan", "Sudan"],
  SE: ["Suède", "Sweden"],
  SG: ["Singapour", "Singapore"],
  SH: ["Sainte-Hélène", "Saint Helena"],
  SI: ["Slovénie", "Slovenia"],
  SJ: ["Svalbard et Île Jan Mayen", "Svalbard and Jan Mayen"],
  SK: ["Slovaquie", "Slovakia"],
  SL: ["Sierra Leone", "Sierra Leone"],
  SM: ["Saint-Marin", "San Marino"],
  SN: ["Sénégal", "Senegal"],
  SO: ["Somalie", "Somalia"],
  SR: ["Suriname", "Suriname"],
  SS: ["Soudan du Sud", "South Sudan"],
  ST: ["São Tomé-et-Principe", "Sao Tome and Principe"],
  SV: ["El Salvador", "El Salvador"],
  SX: ["Saint-Martin (partie néerlandaise)", "Sint Maarten (Dutch part)"],
  SY: ["Syrie", "Syrian Arab Republic"],
  SZ: ["Royaume d'Eswatini", "Eswatini"],
  TC: ["Îles Turques-et-Caïques", "Turks and Caicos Islands"],
  TD: ["Tchad", "Chad"],
  TF: ["Terres australes françaises", "French Southern Territories"],
  TG: ["Togo", "Togo"],
  TH: ["Thaïlande", "Thailand"],
  TJ: ["Tadjikistan", "Tajikistan"],
  TK: ["Tokelau", "Tokelau"],
  TL: ["Timor-Leste", "Timor-Leste"],
  TM: ["Turkménistan", "Turkmenistan"],
  TN: ["Tunisie", "Tunisia"],
  TO: ["Tonga", "Tonga"],
  TR: ["Turquie", "Türkiye"],
  TT: ["Trinité-et-Tobago", "Trinidad and Tobago"],
  TV: ["Tuvalu", "Tuvalu"],
  TW: ["Taïwan", "Taiwan, Province of China"],
  TZ: ["République unie de Tanzanie", "United Republic of Tanzania"],
  UA: ["Ukraine", "Ukraine"],
  UG: ["Ouganda", "Uganda"],
  UM: ["Îles mineures éloignées des États-Unis", "United States Minor Outlying Islands"],
  US: ["États-Unis d'Amérique", "United States of America"],
  UY: ["Uruguay", "Uruguay"],
  UZ: ["Ouzbékistan", "Uzbekistan"],
  VA: ["Saint-Siège (Vatican)", "Holy See (Vatican City State)"],
  VC: ["Saint-Vincent-et-les-Grenadines", "Saint Vincent and the Grenadines"],
  VE: ["Venezuela", "Venezuela"],
  VG: ["Îles vierges britanniques", "Virgin Islands, British"],
  VI: ["Îles vierges américaines", "Virgin Islands, U.S."],
  VN: ["Vietnam", "Vietnam"],
  VU: ["Vanuatu", "Vanuatu"],
  WF: ["Wallis-et-Futuna", "Wallis and Futuna"],
  WS: ["Samoa", "Samoa"],
  XK: ["Kosovo", "Kosovo"],
  YE: ["Yémen", "Yemen"],
  YT: ["Mayotte", "Mayotte"],
  ZA: ["Afrique du Sud", "South Africa"],
  ZM: ["Zambie", "Zambia"],
  ZW: ["Zimbabwe", "Zimbabwe"],
};

/** Drapeau emoji depuis un code pays MRZ (FRA, D…) — indicateurs régionaux Unicode ; vide si inconnu. */
export function flagEmoji(mrzCountryCode: string): string {
  const alpha2 = toAlpha2CountryCode(mrzCountryCode);
  if (!alpha2 || !/^[A-Z]{2}$/.test(alpha2) || alpha2 === "EU") return alpha2 === "EU" ? "🇪🇺" : "";
  return String.fromCodePoint(...[...alpha2].map((ch) => 0x1f1e6 + ch.charCodeAt(0) - 65));
}

